from . import stock_move
from . import stock_warehouse
from . import sale
from . import stock_picking
from . import procurement_rule
from . import purchase
from . import res_partner
from . import stock_location
from . import stock_picking_type
